### ISSUE TITLE
🐛 [firebase_ui_auth] Swift Package Manager (SPM) support

### ISSUE THREAD

**Issue by kuhnroyal** [firebase/FirebaseUI-Flutter#454]
### Is there an existing issue for this?

- [x] I have searched the existing issues and found no duplicates.

### What plugin is this bug for?

Firebase UI OAuth, Firebase UI Auth

### What platform(s) does this bug affect?

macOS, iOS

### List of dependencies used.

<details>
<summary>flutter pub deps -s list</summary>
<pre>
  desktop_webview_auth: 0.0.15
</pre>
</details>

### Steps to reproduce

* enable SPM support for a Flutter app
* add `firebase_ui_auth` or `firebase_ui_oauth`
* the package `firebase_ui_oauth` pulls in https://pub.dev/packages/desktop_webview_auth which does not support SPM 

### Expected Behavior

The package should work with SPM.

### Actual Behavior

The package does not work with SPM.

### Additional Information

I created https://github.com/invertase/flutter_desktop_webview_auth/issues/64 to track SPM support there as well.

**Comment by russellwheatley** [comment]
Open issue on the correct repository: https://github.com/firebase/FirebaseUI-Flutter/issues/454

**Comment by anowotny** [comment]
As of today, Flutter 3.44 defaults to SPM. Any timeline of introducing SPM support for this package?

**Comment by crcdng** [comment]
The main problem appears to be the dependency `firebase_ui_auth` → `firebase_ui_oauth` → `desktop_webview_auth`, a third party package which is [unmaintained](https://github.com/invertase/flutter_desktop_webview_auth) and does not support SPM.

**Comment by large** [comment]
> The main problem appears to be the dependency `firebase_ui_auth` → `firebase_ui_oauth` → `desktop_webview_auth`, a third party package which is [unmaintained](https://github.com/invertase/flutter_desktop_webview_auth) and does not support SPM.

After asking AI how this could be fixed, the reference to iOS can just be removed in pubspec.yaml of desktop_webview_auth:
```yaml
flutter:
  plugin:
    platforms:
      macos:
        pluginClass: DesktopWebviewAuthPlugin
      linux:
        pluginClass: DesktopWebviewAuthPlugin
      windows:
        pluginClass: DesktopWebviewAuthPlugin
      android:
        package: com.example.desktop_webview_auth
        pluginClass: DesktopWebviewAuthPlugin
      web:
        pluginClass: DesktopWebviewAuthWeb
        fileName: desktop_webview_auth_web.dart
```

Just test on locally on your "packages/" directory and it will compile and work.
Then firebase_ui_oauth can be used as before.

>   iOS platform support removed on purpose: firebase_ui_oauth only calls this on
>   desktop platforms (macos/linux/windows) -- iOS/Android use native sign-in instead
>   -- so the iOS plugin registration was dead weight blocking Swift Package Manager
>   adoption (upstream never shipped a Package.swift and the repo is archived).
